"""Change signature field type to Text

Revision ID: 9f45b79f039a
Revises: 989e2be1a6be
Create Date: 2025-03-30 02:12:34.804158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f45b79f039a'
down_revision = '989e2be1a6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_metadata', schema=None) as batch_op:
        batch_op.alter_column('signature',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_metadata', schema=None) as batch_op:
        batch_op.alter_column('signature',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
